<a href="https://colab.research.google.com/github/AeroEng16/machine-learning-with-python-logistic-regression-3211129/blob/main/freeCodeCampMachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tutorial link - https://youtu.be/V_xro1bcAuA
https://learnpytorch.io

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import numpy as np
import pandas
import matplotlib.pyplot as plt
import torch


In [ ]:
print (torch.__version__)

2.0.1+cu118


# Introduction to Tensors<br/>
## Creating Tensors

Pytorch tensors are created using tocher.tensor() = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# Scalar

scalar = torch.tensor(7)
scalar



tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
#Vector

vector = torch.tensor([7,7,7])
vector.shape

torch.Size([3])

In [ ]:
# MATRIX
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix[1,1]
matrix.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [1,2,3],
                        [2,5,4]],
                         [[1,2,3],
                          [1,2,3],
                          [2,5,4]]])
TENSOR[1]

tensor([[1, 2, 3],
        [1, 2, 3],
        [2, 5, 4]])

### Random Tensor

why random tensors?

Random tensors are important becuas eht eway many neural networks learn is that they start with tensors fill of random number sand then adjust those random numbers to better represent the data.


In [ ]:
# Create random tensors

randomTensor = torch.rand([3,4])
randomTensor

tensor([[0.0617, 0.4343, 0.3710, 0.1347],
        [0.3846, 0.1461, 0.4725, 0.7203],
        [0.5824, 0.3359, 0.1425, 0.5054]])

In [ ]:
# Create random tensor with similar shape to image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Zeros and onenes

zeros = torch.zeros(size=[3,4])
zeros
zeros*randomTensor

ones = torch.ones(size=[3,4])
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [ ]:
tensorRange = torch.arange(0,1000,10)

In [ ]:
#Creating tensors-like

rangeZeros = torch.zeros_like(input=tensorRange)
rangeZeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

### Tensor Datatypes

** Note:** Tensor datatypes if one of the 3 biggest error sources you run into with pytorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [ ]:
#Float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float32, # Define tensor datatype
                               device=None,         # Defines what device (i.e. CPU vs. GPU) the tensor is on. Operations between tensors need to be on same device
                               requires_grad=False) # Track the gradients (yes/no)
float_32_tensor.dtype

float_16_tensor=float_32_tensor.type(torch.float16)
product = float_16_tensor*float_32_tensor
product.dtype

torch.float32

## Reshaping, stacking, squeezing and unsqueezing tnesors

* Reshaping - reshapes an input tensor to a defined shape
* view - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack/hstack)
* squeeze - remove all '1' dimensions from a tensor
* unqsqueeze - adds a '1' dimension to a tensor
* permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
x = torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# Change dimensions
x_reshaped=x.reshape(3,3)
x_reshaped,x.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([9]))

In [ ]:
# Change view

z = x.view(1,9)
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x as a view of a tensor shares the same memory as the original tensor

z[:,0]=5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# Stack on top of each other

x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
# torch.squeeze remove all 1 dimensions from tensor

x_squeeze = torch.squeeze(x)
x_squeeze,x.shape,x_squeeze.shape

(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]), torch.Size([9]))

## Pytorch tensors & numpy

* data in numpy want in torch -. torch.from_numpy(ndarray)
* tensor-> numpy torch.Tensor.numpy()

In [ ]:
array = np.arange(1,10)
tensor = torch.from_numpy(array) # warning when converting from numpy to pytorch, pytorch reflects numpy default float 64 unless specified otherwise
array,tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# Change value of array

array = array+1
array,tensor

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# Tensor to numpy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take random out of random)

In short neural network starts with random numbers, tensor operations, update random numbers to try and better represent data -> again -> again -> again.



In [1]:
import torch
torch.rand(1)


tensor([0.2141])

In [10]:
torch.manual_seed(0)
tensor = torch.rand(7,7)
tensor,tensor.shape
torch.manual_seed(0)
tensor_2  = torch.rand(1,7)
tensor_2.reshape(7,1)
tensor_2*tensor

tensor([[0.2463, 0.5902, 0.0078, 0.0174, 0.0945, 0.4021, 0.2402],
        [0.4449, 0.3500, 0.0559, 0.0461, 0.1235, 0.0142, 0.0828],
        [0.1458, 0.3983, 0.0617, 0.1056, 0.0495, 0.1790, 0.3341],
        [0.4542, 0.3051, 0.0773, 0.0554, 0.1700, 0.6041, 0.0177],
        [0.0919, 0.2869, 0.0270, 0.1231, 0.0541, 0.1711, 0.0738],
        [0.0157, 0.1599, 0.0823, 0.0955, 0.2282, 0.3337, 0.1194],
        [0.2901, 0.0255, 0.0123, 0.0320, 0.2507, 0.5029, 0.1364]])

In [22]:
torch.cuda.manual_seed(1234)

tensor1_GPU = torch.rand(2,3,device="cuda")
tensor2_GPU = torch.rand(2,3,device="cuda").reshape(3,2)

product = torch.matmul(tensor1_GPU,tensor2_GPU)

In [28]:
max = product.max()
min = product.min()
maxIndex = product.argmax()
minIndex = product.argmin()
product, max,maxIndex,min,minIndex

(tensor([[0.7154, 0.2908],
         [1.1616, 0.3998]], device='cuda:0'),
 tensor(1.1616, device='cuda:0'),
 tensor(2, device='cuda:0'),
 tensor(0.2908, device='cuda:0'),
 tensor(1, device='cuda:0'))

In [33]:
torch.manual_seed(7)
tensor3 = torch.rand(1,1,1,10)
tensor3Squeezed = tensor3.squeeze()

tensor3,tensor3.shape,tensor3Squeezed,tensor3Squeezed.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))